[build]
  command = "cd portfolio/projects/storybook/netlify/functions && npm install"
  publish = "portfolio/projects/storybook"
  functions = "portfolio/projects/storybook/netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Default page redirect
[[redirects]]
  from = "/"
  to = "/simple.html"
  status = 301